insert into users (id, user_name, password) values (1, 'admin', '$2a$04$JCHV7CDxPklUxyizBGVsneWhBkAmMFpt3gdGmLsKRjf4KRU0OO3zS')
insert into users (id, user_name, password) values (2, 'user', '$2a$04$5G9/akPFA7dOJn19m0aZ.Oyn65QQdSzrkGBTjsBjgnIeCjPhv0DWq')
insert into roles(id, role_name) values (1,'ROLE_ADMIN')
insert into roles(id, role_name) values (2,'ROLE_USER')
insert into users_roles(user_id, roles_id) values (1,1)
insert into users_roles(user_id, roles_id) values (2,2)
insert into customers (id, customer_name, surname, photo_url, creator_user_id, last_modification_user_id) values (1, 'Customer1', 'Custom','https://openclipart.org/download/247324/abstract-user-flat-1.svg', 1, 2)
insert into customers (id, customer_name, surname, photo_url, creator_user_id, last_modification_user_id) values (2, 'Customer2', 'Custom','https://openclipart.org/download/247324/abstract-user-flat-1.svg', 1, 1)
insert into customers (id, customer_name, surname, photo_url, creator_user_id, last_modification_user_id) values (3, 'Customer3', 'Custom','https://openclipart.org/download/247324/abstract-user-flat-1.svg', 2, 1)
insert into customers (id, customer_name, surname, photo_url, creator_user_id, last_modification_user_id) values (4, 'Customer4', 'Custom','https://openclipart.org/download/247324/abstract-user-flat-1.svg', 2, 2)